### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nikita-moor** [tommasospinelli/Online-Dictionary-of-Latin-Near-Synonyms#1]
Dear Tommaso Spinelli,

I hold a collection of [dictionaries of Latin synonyms][1] and would like to share your wordlist too. Could you, please, add license agreement allowing (or prohibiting) redistributing of your data.

[1]: https://nikita-moor.github.io/dictionaries/dictionaries.html

**Comment by tommasospinelli** [comment]
Dear Nikita, Thanks for your email. Your database of Latin tools looks amazing! Yes you can  add my dictionary to your list. Please reference it in this way:
Spinelli, T., Fenzi G. 2018. Online Dictionary of Latin Near-Synonyms. St Andrews University. Doi https://doi.org/10.17630/3cf644e6-86b8-44d0-a50a-b33c7ca86072. 
And put there a link to my github repository. 
All the bestTommaso

Sent from Yahoo Mail on Android 
 
  On Sat, 4 Jan 2020 at 17:05, Nikita Moor<notifications@github.com> wrote:   
Dear Tommaso Spinelli,

I hold a collection of dictionaries of Latin synonyms and would like to share your wordlist too. Could you, please, add license agreement allowing (or prohibiting) redistributing of your data.

**Comment by nikita-moor** [comment]
Here is [our version][1] of your dictionary. Feel free to contact us, if you find errors in the description or incorrect referencing. Also, it would be better, if you choose a license for your data, then other researchers and developers could reuse it easier.

Also, I would like to propose you [corrected data file][2], including fixed misprints, unified "indecl." and "indeclinabile" spelling, and reformatted for more consistent parsing (duplicated records were remained):

For example, original:

```json
"ex": [
  "de [f. e n. indeclinabile]",
  "e [+ ablativo plurale o genitivo plurale]",
  "a [f. e n. indecl.]"
],
```

Changed:

```json
"ex": [
  "de [indeclinabile, f. e n.]",
  "e [] + ablativo plurale o genitivo plurale",
  "a [indeclinabile, f. e n.]"
],
```

If you are going to further develop your database, I would recommend to make the dictionary completely monolingual and rewrite "ablativo plurale o genitivo plurale" on Latin language.

[1]: https://nikita-moor.github.io/dictionaries/dictionaries/Spinelli2019.html
[2]: https://github.com/nikita-moor/latin-dictionary/tree/master/Spinelli2019

**Comment by tommasospinelli** [comment]
Dear Nikita, Thanks for this wonderful work that you have done on the dictionary. Yes that is still the beta version, but I am rewriting the dictionary to publish it (with some 2000 more headwords) as an aademic monograph. I will send you the link when it s done. All the best Tommaso 

Sent from Yahoo Mail on Android 
 
  On Tue, 14 Jan 2020 at 14:53, Nikita Moor<notifications@github.com> wrote:   
Here is our version of your dictionary. Feel free to contact us, if you find errors in the description or incorrect referencing. Also, it would be better, if you choose a license for your data, then other researchers and developers could reuse it easier.

Also, I would like to propose you corrected data file, including fixed misprints, unified "indecl." and "indeclinabile" spelling, and reformatted for more consistent parsing (duplicated records were remained):

For example, original:
"ex": [
  "de [f. e n. indeclinabile]",
  "e [+ ablativo plurale o genitivo plurale]",
  "a [f. e n. indecl.]"
],
Changed:
"ex": [
  "de [indeclinabile, f. e n.]",
  "e [] + ablativo plurale o genitivo plurale",
  "a [indeclinabile, f. e n.]"
],
If you are going to further develop your database, I would recommend to make the dictionary completely monolingual and rewrite "ablativo plurale o genitivo plurale" on Latin language.
